public enum ASSET_KEY : ushort
{
    // Material
    MATERI_LEVEL_0,
    MATERI_LEVEL_1,
    MATERI_LEVEL_2,
    MATERI_LEVEL_3,
    MATERI_LEVEL_4,
    MATERI_LEVEL_5,
    MATERI_LEVEL_6,
    MATERI_LEVEL_7,
    MATERI_LEVEL_8,
    MATERI_LEVEL_9,
    MATERI_LEVEL_10,

    // Level Header
    HEADER_LEVEL_0,
    HEADER_LEVEL_1,
    HEADER_LEVEL_2,
    HEADER_LEVEL_3,
    HEADER_LEVEL_4,
    HEADER_LEVEL_5,
    HEADER_LEVEL_6,
    HEADER_LEVEL_7,
    HEADER_LEVEL_8,
    HEADER_LEVEL_9,
    HEADER_LEVEL_10,

    // Level Select Config
    LEVEL_SELECT_JSON,
    LEVEL_CONFIG_JSON,
}

public enum ASSET_TYPE
{
    IMAGE,
    TEXT,
}
